/* ==========================================================================
   VENDORED FROM zaneysudoku/index.html — DO NOT EDIT THIS FILE.

   The deterministic puzzle generator, copied verbatim so that a book dealt
   today can be reprinted years from now byte for byte. Editing it here would
   silently change every puzzle in every book in books.json.

   Re-sync with:  python3 dev/sync-engine.py --from ../zaneysudoku/index.html
   sha256: ac7be14aa38b99fcf389da7702b7986b76f484849be0320997e38e0de2da8c2b
   ========================================================================== */

/* =====================================================================
   PUZZLE ENGINE
   Deterministic: puzzle N at difficulty D is identical on every device.
   Guaranteed finishable: cages are carved from a real solved grid, so a
   solution always exists; a counting solver then verifies uniqueness,
   splitting cages deterministically until exactly one solution remains.
   ===================================================================== */

const DIFFS = ["easy","medium","hard","expert","nightmare"];
const DIFF_CFG = {
  easy:   { sizes:[1,2,2,2,3,3], mergeSingles:false, maxMerge:0, reveal:5 },
  medium: { sizes:[2,2,3,3,3,4], mergeSingles:true,  maxMerge:4, reveal:0 },
  hard:   { sizes:[2,3,3,4,4,5], mergeSingles:true,  maxMerge:5, reveal:0 },
  expert: { sizes:[3,4,4,5,5,6], mergeSingles:true,  maxMerge:6, reveal:0 },
  nightmare:{ sizes:[4,5,5,6,6,7], mergeSingles:true, maxMerge:7, reveal:0 }
};
const DIFF_LABEL = { easy:"Easy", medium:"Medium", hard:"Hard", expert:"Expert", nightmare:"Nightmare", cowards:"Coward's" };
const CLASSIC_DIFFS = ["cowards","easy","medium","hard"];
const CLASSIC_CLUES = { cowards:47, easy:40, medium:32, hard:26 };
const X_DIFFS = ["easy","medium","hard","expert"];
const X_CLUES = { easy:38, medium:31, hard:26, expert:22 };
const H_DIFFS = ["easy","medium","hard","expert"];
const H_CLUES = { easy:38, medium:31, hard:26, expert:23 };
function hyperWin(r,c){
  const wr=(r>=1&&r<=3)?0:(r>=5&&r<=7)?1:-1;
  const wc=(c>=1&&c<=3)?0:(c>=5&&c<=7)?1:-1;
  return (wr<0||wc<0)?-1:wr*2+wc;
}
const MAX_NUM = 100000;

function mulberry32(a){return function(){a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
function seedFor(num,diff){let h=num>>>0;h=Math.imul(h^0x9E3779B9,2654435761)>>>0;h=(h^Math.imul(DIFFS.indexOf(diff)+1,0x85EBCA6B))>>>0;return h||1;}
function shuffle(a,rng){for(let i=a.length-1;i>0;i--){const j=(rng()*(i+1))|0;const t=a[i];a[i]=a[j];a[j]=t;}return a;}
function neighbors(c){const r=(c/9)|0,k=c%9,out=[];if(r>0)out.push(c-9);if(r<8)out.push(c+9);if(k>0)out.push(c-1);if(k<8)out.push(c+1);return out;}
function connectedSet(cells){if(cells.length<=1)return true;const set=new Set(cells),seen=new Set([cells[0]]),q=[cells[0]];while(q.length){const c=q.pop();for(const n of neighbors(c))if(set.has(n)&&!seen.has(n)){seen.add(n);q.push(n);}}return seen.size===cells.length;}

/* Complete solved grid via seeded backtracking */
function genSolution(rng,useX,useH){
  const g=new Uint8Array(81),rows=new Int16Array(9),cols=new Int16Array(9),boxes=new Int16Array(9);
  const diag=new Int16Array(2),wins=new Int16Array(4);
  const digits=[1,2,3,4,5,6,7,8,9];
  function fill(i){
    if(i===81)return true;
    const r=(i/9)|0,c=i%9,b=((r/3)|0)*3+((c/3)|0);
    const on0=useX&&r===c,on1=useX&&r+c===8;
    const w=useH?hyperWin(r,c):-1;
    const order=shuffle(digits.slice(),rng);
    for(const d of order){
      const bit=1<<d;
      if((rows[r]|cols[c]|boxes[b])&bit)continue;
      if(on0&&(diag[0]&bit))continue;
      if(on1&&(diag[1]&bit))continue;
      if(w>=0&&(wins[w]&bit))continue;
      rows[r]|=bit;cols[c]|=bit;boxes[b]|=bit;g[i]=d;
      if(on0)diag[0]|=bit;if(on1)diag[1]|=bit;if(w>=0)wins[w]|=bit;
      if(fill(i+1))return true;
      rows[r]^=bit;cols[c]^=bit;boxes[b]^=bit;g[i]=0;
      if(on0)diag[0]^=bit;if(on1)diag[1]^=bit;if(w>=0)wins[w]^=bit;
    }
    return false;
  }
  fill(0);
  return g;
}

/* Carve the grid into cages. No digit repeats within a cage (checked
   against the solution), so the killer rule always holds. */
function buildCages(sol,rng,cfg){
  const cageOf=new Int16Array(81).fill(-1);
  const list=[];
  const order=shuffle([...Array(81).keys()],rng);
  for(const s of order){
    if(cageOf[s]!==-1)continue;
    const id=list.length,cells=[s];cageOf[s]=id;
    let digs=1<<sol[s];
    const target=cfg.sizes[(rng()*cfg.sizes.length)|0];
    while(cells.length<target){
      const opts=[];
      for(const c of cells)for(const n of neighbors(c))
        if(cageOf[n]===-1&&!(digs&(1<<sol[n]))&&opts.indexOf(n)===-1)opts.push(n);
      if(!opts.length)break;
      const p=opts[(rng()*opts.length)|0];
      cageOf[p]=id;cells.push(p);digs|=1<<sol[p];
    }
    list.push(cells);
  }
  if(cfg.mergeSingles){
    for(let id=0;id<list.length;id++){
      if(list[id].length!==1)continue;
      const c=list[id][0],dbit=1<<sol[c];
      for(const n of neighbors(c)){
        const t=cageOf[n];if(t===id)continue;
        const tc=list[t];if(!tc.length||tc.length>=cfg.maxMerge)continue;
        let digs=0;for(const x of tc)digs|=1<<sol[x];
        if(digs&dbit)continue;
        tc.push(c);cageOf[c]=t;list[id]=[];break;
      }
    }
  }
  const cages=[];
  for(const cells of list){
    if(!cells.length)continue;
    cells.sort((a,b)=>a-b);
    cages.push({cells,sum:cells.reduce((s,c)=>s+sol[c],0)});
  }
  const cOf=new Int16Array(81);
  cages.forEach((g,i)=>g.cells.forEach(c=>cOf[c]=i));
  return {cages,cageOf:cOf};
}

/* Count solutions (stop at 2). MRV cell selection + cage sum bounds. */
function countSolutions(cages,cageOf,limit,budget){
  limit=limit||2;budget=budget||40000;
  const rows=new Int16Array(9),cols=new Int16Array(9),boxes=new Int16Array(9);
  const used=new Int16Array(cages.length),left=new Int16Array(cages.length),rem=new Int16Array(cages.length);
  cages.forEach((g,i)=>{left[i]=g.cells.length;rem[i]=g.sum;});
  const val=new Uint8Array(81);
  let count=0,nodes=0,abort=false;
  const sols=[];
  function boundsOK(mask,k,target){
    if(k===0)return target===0;
    let mn=0,n=0;
    for(let d=1;d<=9&&n<k;d++)if(!(mask&(1<<d))){mn+=d;n++;}
    if(n<k||mn>target)return false;
    let mx=0;n=0;
    for(let d=9;d>=1&&n<k;d--)if(!(mask&(1<<d))){mx+=d;n++;}
    return mx>=target;
  }
  function cand(i){
    const r=(i/9)|0,c=i%9,b=((r/3)|0)*3+((c/3)|0),g=cageOf[i];
    let m=0;
    for(let d=1;d<=9;d++){
      const bit=1<<d;
      if((rows[r]|cols[c]|boxes[b]|used[g])&bit)continue;
      const rr=rem[g]-d;
      if(rr<0)continue;
      if(!boundsOK(used[g]|bit,left[g]-1,rr))continue;
      m|=bit;
    }
    return m;
  }
  function search(){
    if(abort||count>=limit)return;
    if(++nodes>budget){abort=true;return;}
    let best=-1,bm=0,bc=10;
    for(let i=0;i<81;i++){
      if(val[i])continue;
      const m=cand(i);
      let c=0;for(let d=1;d<=9;d++)if(m&(1<<d))c++;
      if(c===0)return;
      if(c<bc){bc=c;best=i;bm=m;if(c===1)break;}
    }
    if(best===-1){count++;if(sols.length<2)sols.push(val.slice());return;}
    const r=(best/9)|0,c=best%9,b=((r/3)|0)*3+((c/3)|0),g=cageOf[best];
    for(let d=1;d<=9;d++){
      const bit=1<<d;
      if(!(bm&bit))continue;
      val[best]=d;rows[r]|=bit;cols[c]|=bit;boxes[b]|=bit;used[g]|=bit;rem[g]-=d;left[g]--;
      search();
      val[best]=0;rows[r]^=bit;cols[c]^=bit;boxes[b]^=bit;used[g]^=bit;rem[g]+=d;left[g]++;
      if(abort||count>=limit)return;
    }
  }
  search();
  return {count,aborted:abort,sols};
}

/* Carve one cell out of its cage into a singleton (its sum pins the true
   digit, killing the alternative solution). Remaining cells re-form as
   connected cages. Deterministic. */
function peelCell(P,c){
  const gi=P.cageOf[c],g=P.cages[gi];
  if(g.cells.length<2)return false;
  const rest=g.cells.filter(x=>x!==c);
  const parts=[[c]];
  const remaining=new Set(rest);
  while(remaining.size){
    const start=remaining.values().next().value;
    const comp=[start];remaining.delete(start);
    const q=[start];
    while(q.length){
      const x=q.pop();
      for(const n of neighbors(x))if(remaining.has(n)){remaining.delete(n);comp.push(n);q.push(n);}
    }
    comp.sort((a,b)=>a-b);
    parts.push(comp);
  }
  P.cages.splice(gi,1,...parts.map(cells=>({cells,sum:cells.reduce((s,x)=>s+P.sol[x],0)})));
  P.cages.forEach((cg,i)=>cg.cells.forEach(x=>P.cageOf[x]=i));
  return true;
}

/* Deterministically split the largest cage: peel off a cell whose removal
   keeps the cage connected. Every split adds information, so the loop
   converges to a unique solution. */
function splitOne(P){
  let bi=-1;
  for(let i=0;i<P.cages.length;i++){
    const L=P.cages[i].cells.length;
    if(L<2)continue;
    if(bi===-1||L>P.cages[bi].cells.length)bi=i;
  }
  if(bi===-1)return false;
  const g=P.cages[bi];
  for(let k=g.cells.length-1;k>=0;k--){
    const c=g.cells[k];
    const rest=g.cells.filter(x=>x!==c);
    if(connectedSet(rest)){
      g.cells=rest;g.sum-=P.sol[c];
      P.cages.push({cells:[c],sum:P.sol[c]});
      P.cageOf[c]=P.cages.length-1;
      return true;
    }
  }
  return false;
}

function dealPuzzle(num,diff){
  const rng=mulberry32(seedFor(num,diff));
  const sol=genSolution(rng);
  const cfg=DIFF_CFG[diff];
  const built=buildCages(sol,rng,cfg);
  const P={sol,cages:built.cages,cageOf:built.cageOf};
  for(let a=0;a<80;a++){
    const r=countSolutions(P.cages,P.cageOf);
    if(r.count===1&&!r.aborted)break;
    if(r.count>=2&&r.sols.length===2){
      let pick=-1;
      for(let i=0;i<81;i++)if(r.sols[0][i]!==r.sols[1][i]){pick=i;break;}
      if(pick>=0&&peelCell(P,pick))continue;
    }
    if(!splitOne(P))break;
  }
  const given=new Uint8Array(81);
  if(cfg.reveal){
    const ord=shuffle([...Array(81).keys()],rng);
    for(let i=0;i<cfg.reveal;i++)given[ord[i]]=1;
  }
  return {num,diff,sol,cages:P.cages,cageOf:P.cageOf,given};
}

/* ============ classic (cage-free) sudoku ============ */
function countClassic(vals,limit,budget,useX,useH){
  limit=limit||2;budget=budget||20000;
  const rows=new Int16Array(9),cols=new Int16Array(9),boxes=new Int16Array(9),diag=new Int16Array(2),wins=new Int16Array(4);
  const val=Uint8Array.from(vals);
  const dm=(r,c)=>(useX?((r===c?1:0)|(r+c===8?2:0)):0);
  const wm=(r,c)=>(useH?hyperWin(r,c):-1);
  for(let i=0;i<81;i++)if(val[i]){
    const r=(i/9)|0,c=i%9,b=((r/3)|0)*3+((c/3)|0),bit=1<<val[i];
    rows[r]|=bit;cols[c]|=bit;boxes[b]|=bit;
    const k=dm(r,c);if(k&1)diag[0]|=bit;if(k&2)diag[1]|=bit;
    const w=wm(r,c);if(w>=0)wins[w]|=bit;
  }
  let count=0,nodes=0,abort=false;
  function mask(r,c,b){
    let m=rows[r]|cols[c]|boxes[b];
    const k=dm(r,c);if(k&1)m|=diag[0];if(k&2)m|=diag[1];
    const w=wm(r,c);if(w>=0)m|=wins[w];
    return m;
  }
  function search(){
    if(abort||count>=limit)return;
    if(++nodes>budget){abort=true;return;}
    let best=-1,bm=0,bc=10;
    for(let i=0;i<81;i++){
      if(val[i])continue;
      const r=(i/9)|0,c=i%9,b=((r/3)|0)*3+((c/3)|0);
      const used=mask(r,c,b);
      let m=0,cnt=0;
      for(let d=1;d<=9;d++){const bit=1<<d;if(!(used&bit)){m|=bit;cnt++;}}
      if(cnt===0)return;
      if(cnt<bc){bc=cnt;best=i;bm=m;if(cnt===1)break;}
    }
    if(best===-1){count++;return;}
    const r=(best/9)|0,c=best%9,b=((r/3)|0)*3+((c/3)|0),k=dm(r,c),w=wm(r,c);
    for(let d=1;d<=9;d++){
      const bit=1<<d;if(!(bm&bit))continue;
      val[best]=d;rows[r]|=bit;cols[c]|=bit;boxes[b]|=bit;
      if(k&1)diag[0]|=bit;if(k&2)diag[1]|=bit;if(w>=0)wins[w]|=bit;
      search();
      val[best]=0;rows[r]^=bit;cols[c]^=bit;boxes[b]^=bit;
      if(k&1)diag[0]^=bit;if(k&2)diag[1]^=bit;if(w>=0)wins[w]^=bit;
      if(abort||count>=limit)return;
    }
  }
  search();
  return {count,aborted:abort};
}
/* Solvable with naked + hidden singles alone - the Coward's guarantee */
function singlesSolvable(vals){
  const val=Uint8Array.from(vals);
  const rows=new Int16Array(9),cols=new Int16Array(9),boxes=new Int16Array(9);
  const bx=i=>((((i/9)|0)/3)|0)*3+(((i%9)/3)|0);
  let filled=0;
  for(let i=0;i<81;i++)if(val[i]){
    const bit=1<<val[i];rows[(i/9)|0]|=bit;cols[i%9]|=bit;boxes[bx(i)]|=bit;filled++;
  }
  const put=(i,d)=>{const bit=1<<d;val[i]=d;rows[(i/9)|0]|=bit;cols[i%9]|=bit;boxes[bx(i)]|=bit;filled++;};
  let moved=true;
  while(moved&&filled<81){
    moved=false;
    for(let i=0;i<81;i++){
      if(val[i])continue;
      const r=(i/9)|0,c=i%9,b=bx(i);
      let cnt=0,dd=0;
      for(let d=1;d<=9;d++)if(!((rows[r]|cols[c]|boxes[b])&(1<<d))){cnt++;dd=d;}
      if(cnt===1){put(i,dd);moved=true;}
      else if(cnt===0)return false;
    }
    if(!moved){
      const units=[];
      for(let r=0;r<9;r++){const u=[];for(let c=0;c<9;c++)u.push(r*9+c);units.push(u);}
      for(let c=0;c<9;c++){const u=[];for(let r=0;r<9;r++)u.push(r*9+c);units.push(u);}
      for(let b=0;b<9;b++){const br=((b/3)|0)*3,bc=(b%3)*3,u=[];
        for(let r=0;r<3;r++)for(let c=0;c<3;c++)u.push((br+r)*9+bc+c);units.push(u);}
      for(const u of units){
        for(let d=1;d<=9;d++){
          const bit=1<<d;let pos=-1,n=0,present=false;
          for(const i of u){
            if(val[i]===d){present=true;break;}
            if(val[i])continue;
            if(!((rows[(i/9)|0]|cols[i%9]|boxes[bx(i)])&bit)){n++;pos=i;}
          }
          if(!present&&n===1){put(pos,d);moved=true;}
        }
      }
    }
  }
  return filled===81;
}
function dealClassic(num,diff){
  const base=seedFor(num,"easy");
  const rng=mulberry32(((base ^ Math.imul(CLASSIC_DIFFS.indexOf(diff)+11,0xC2B2AE3D))>>>0)||7);
  const sol=genSolution(rng);
  const target=CLASSIC_CLUES[diff];
  const vals=Uint8Array.from(sol);
  const order=shuffle([...Array(81).keys()],rng);
  let clues=81;
  for(const i of order){
    if(clues<=target)break;
    const keep=vals[i];vals[i]=0;
    const r=countClassic(vals);
    let ok=r.count===1&&!r.aborted;
    if(ok&&diff==="cowards")ok=singlesSolvable(vals);
    if(ok)clues--;else vals[i]=keep;
  }
  const given=new Uint8Array(81);
  for(let i=0;i<81;i++)if(vals[i])given[i]=1;
  return {num,diff,kind:"classic",sol,cages:[],cageOf:new Int16Array(81).fill(-1),given};
}

function dealX(num,diff){
  const base=seedFor(num,"medium");
  const rng=mulberry32(((base ^ Math.imul(X_DIFFS.indexOf(diff)+29,0x27D4EB2F))>>>0)||13);
  const sol=genSolution(rng,true);
  const target=X_CLUES[diff];
  const vals=Uint8Array.from(sol);
  const order=shuffle([...Array(81).keys()],rng);
  let clues=81;
  for(const i of order){
    if(clues<=target)break;
    const keep=vals[i];vals[i]=0;
    const r=countClassic(vals,2,40000,true);
    if(r.count===1&&!r.aborted)clues--;else vals[i]=keep;
  }
  const given=new Uint8Array(81);
  for(let i=0;i<81;i++)if(vals[i])given[i]=1;
  return {num,diff,kind:"x",sol,cages:[],cageOf:new Int16Array(81).fill(-1),given};
}

function dealHyper(num,diff){
  const base=seedFor(num,"hard");
  const rng=mulberry32(((base ^ Math.imul(H_DIFFS.indexOf(diff)+53,0x165667B1))>>>0)||17);
  const sol=genSolution(rng,false,true);
  const target=H_CLUES[diff];
  const vals=Uint8Array.from(sol);
  const order=shuffle([...Array(81).keys()],rng);
  let clues=81;
  for(const i of order){
    if(clues<=target)break;
    const keep=vals[i];vals[i]=0;
    const r=countClassic(vals,2,40000,false,true);
    if(r.count===1&&!r.aborted)clues--;else vals[i]=keep;
  }
  const given=new Uint8Array(81);
  for(let i=0;i<81;i++)if(vals[i])given[i]=1;
  return {num,diff,kind:"hyper",sol,cages:[],cageOf:new Int16Array(81).fill(-1),given};
}

/* Daily: number + difficulty derive from the UTC date */
const DAILY_EPOCH=Date.UTC(2026,0,1);
function dailyDiffFor(dayN){
  const wd=new Date(DAILY_EPOCH+(dayN-1)*86400000).getUTCDay(); // 0 Sun … 6 Sat
  return (wd===1||wd===2)?"easy":(wd===3||wd===4)?"medium":(wd===5||wd===6)?"hard":"expert";
}
function dailyInfo(){
  const dayN=Math.floor((Date.now()-DAILY_EPOCH)/86400000)+1;
  return {dayN,num:900000+dayN,diff:dailyDiffFor(dayN)};
}
function dailyClassicDiff(dayN){
  const wd=new Date(DAILY_EPOCH+(dayN-1)*86400000).getUTCDay();
  return (wd===1||wd===2)?"easy":(wd===3||wd===4)?"medium":"hard";
}
function dailyXDiff(dayN){return dailyDiffFor(dayN);}
function dailyHyperDiff(dayN){return dailyDiffFor(dayN);}

/* Par times are our own target benchmarks per mode/difficulty (seconds), not
   crowd-sourced averages — the site has no server collecting player times. */
const PAR={
  killer:{easy:300,medium:600,hard:900,expert:1500,nightmare:2400},
  classic:{cowards:240,easy:300,medium:480,hard:720},
  x:{easy:360,medium:540,hard:840,expert:1200},
  hyper:{easy:360,medium:540,hard:840,expert:1200}
};