#!/usr/bin/env python3
"""Bake the imprint mark into assets.js.

The artwork arrives as a large RGBA PNG with a transparent background. A book
interior is printed in black ink on white paper, so the alpha is flattened onto
white here rather than left for the PDF to guess at, the image is trimmed to its
own ink, and it is reduced to 8-bit greyscale at a size that is still generous
at print resolution but does not bloat every PDF that carries it.

  python3 dev/build-kdp-assets.py            rebuild assets.js
  python3 dev/build-kdp-assets.py --check    rebuild in memory and diff

--check is the important one: it proves the committed assets.js is exactly what
this script produces, so nobody has to trust that it was regenerated.
"""
import base64, io, os, sys, hashlib

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "dev", "imprint-mark.png")
OUT = os.path.join(ROOT, "assets.js")
TARGET_W = 900          # ~750 dpi at the 1.2in it prints at


def build():
    im = Image.open(SRC)
    if im.mode != "RGBA":
        im = im.convert("RGBA")
    # Flatten onto white: transparent pixels become paper, not black.
    flat = Image.new("RGBA", im.size, (255, 255, 255, 255))
    flat.alpha_composite(im)
    g = flat.convert("L")
    # Trim to the ink. The artwork is centred in a large square canvas and the
    # empty margin would otherwise be printed as blank space.
    inv = g.point(lambda v: 255 - v)
    box = inv.getbbox()
    if box:
        g = g.crop(box)
    w, h = g.size
    g = g.resize((TARGET_W, max(1, round(h * TARGET_W / w))), Image.LANCZOS)
    buf = io.BytesIO()
    # optimize=True is deterministic for a given Pillow build; the --check run
    # is what catches it if that ever stops being true.
    g.save(buf, format="PNG", optimize=True)
    png = buf.getvalue()
    # A full data URL: jsPDF accepts one directly and there is then no doubt
    # anywhere about what the string is.
    b64 = "data:image/png;base64," + base64.b64encode(png).decode("ascii")
    lines = [b64[i:i + 96] for i in range(0, len(b64), 96)]
    js = (
        "/* GENERATED by dev/build-kdp-assets.py — do not edit by hand.\n"
        "   The Zaney Sudoku imprint mark, flattened onto white, trimmed to its\n"
        "   own ink and reduced to 8-bit greyscale for black-ink printing.\n"
        "   %d x %d px, %d bytes of PNG. */\n"
        "window.KDP_ASSETS = {\n"
        "  imprintW: %d, imprintH: %d,\n"
        "  imprint:\n    \"%s\"\n};\n"
    ) % (g.size[0], g.size[1], len(png), g.size[0], g.size[1],
         "\" +\n    \"".join(lines))
    return js, g.size, len(png)


if __name__ == "__main__":
    js, size, nbytes = build()
    if "--check" in sys.argv:
        have = io.open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if have != js:
            print("  assets.js does NOT match a fresh build from dev/imprint-mark.png")
            print("  rebuild with: python3 dev/build-kdp-assets.py")
            sys.exit(1)
        print("  assets.js reproduces exactly (%dx%d, %d bytes of PNG)" % (size[0], size[1], nbytes))
    else:
        io.open(OUT, "w", encoding="utf-8").write(js)
        print("wrote assets.js — %dx%d, %d bytes of PNG" % (size[0], size[1], nbytes))
