#!/usr/bin/env python3
"""
Build fonts.js from dev/inter.woff2.

jsPDF cannot embed woff2, and it cannot embed a variable font. This instances
the variable Inter at two static weights, subsets to the characters a print
interior actually uses, and emits base64 TTFs as a lazily-loaded JS file.

Run from the repo root:  python3 dev/build-kdp-fonts.py
Requires:                pip install fonttools brotli
"""
import argparse, base64, io, json, os, sys
from fontTools.ttLib import TTFont
from fontTools import subset
from fontTools.varLib import instancer

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC  = os.path.join(os.path.dirname(os.path.abspath(__file__)), "inter.woff2")
OUT  = os.path.join(ROOT, "fonts.js")

# Everything a book interior can print: digits, Latin, punctuation, the
# typographic marks the front matter uses, and a little accented Latin so a
# name in the copyright page cannot blow up the subset.
CHARS = (
    "0123456789"
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    "abcdefghijklmnopqrstuvwxyz"
    " !\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~"
    " £©®°·×÷"
    "‐‑‒–—‘’“”•…′″‹›"
    "€™½¼¾"
    "ÀÁÂÄÇÈÉÊËÍÑÓÔÖÚÜß"
    "àáâäçèéêëíñóôöúü"
)

WEIGHTS = [(400, "regular"), (700, "bold")]

# fontTools stamps head.modified with the build time. That lands inside the
# embedded FontFile2, so a font rebuild silently changes every exported PDF and
# a reprint stops matching what is in the shops. Pinned to a constant instead.
# 2020-01-01T00:00:00Z in the OpenType epoch (seconds since 1904-01-01).
FIXED_HEAD_TIME = 3660249600


def build_one(wght):
    f = TTFont(SRC, recalcTimestamp=False)
    f.flavor = None
    inst = instancer.instantiateVariableFont(
        f, {"wght": wght, "opsz": 14}, inplace=False, updateFontNames=False
    )
    buf = io.BytesIO()
    inst.save(buf)
    buf.seek(0)

    opts = subset.Options()
    opts.layout_features = []
    opts.name_IDs = [1, 2, 3, 4, 6]
    opts.notdef_outline = True
    opts.recalc_bounds = True
    opts.drop_tables += ["GSUB", "GPOS", "GDEF", "STAT", "MVAR", "HVAR", "avar", "fvar", "gvar"]

    font = TTFont(buf, recalcTimestamp=False)
    s = subset.Subsetter(options=opts)
    s.populate(text=CHARS)
    s.subset(font)

    font["head"].created = FIXED_HEAD_TIME
    font["head"].modified = FIXED_HEAD_TIME

    out = io.BytesIO()
    font.save(out)
    data = out.getvalue()
    return data, font["maxp"].numGlyphs


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="rebuild in memory and fail if it differs from the committed file")
    args = ap.parse_args()

    if not os.path.exists(SRC):
        sys.exit("missing " + SRC)
    blobs, report, charsets = {}, [], []
    for wght, label in WEIGHTS:
        data, n = build_one(wght)
        blobs[label] = base64.b64encode(data).decode("ascii")
        report.append("  %-7s wght %d  %5d bytes  %d glyphs" % (label, wght, len(data), n))
        f = TTFont(io.BytesIO(data), recalcTimestamp=False)
        charsets.append(set(f.getBestCmap().keys()))

    # Only characters present in EVERY weight are safe to print, and the source
    # dev/inter.woff2 is itself a web subset — anything it lacks silently
    # renders as nothing. The exporter checks every string against this before
    # composing, so a missing glyph is a loud abort rather than a hole on page 3.
    common = sorted(set.intersection(*charsets))
    charset = "".join(chr(c) for c in common)
    missing = sorted(set(ord(c) for c in CHARS) - set(common))
    if missing:
        report.append("  NOT in dev/inter.woff2, so unavailable to the interior: " +
                      " ".join("%s (U+%04X)" % (chr(m), m) for m in missing))

    body = [
        "/* Generated by tools/build-kdp-fonts.py — do not edit by hand.",
        " * Inter, instanced from the variable dev/inter.woff2 and subset to the",
        " * print-interior charset. jsPDF cannot embed woff2 or variable fonts, and",
        " * its built-in base-14 faces are not embedded at all, which KDP rejects.",
        " * Loaded on demand by the KDP interior exporter only. */",
        "window.KDP_FONTS = {",
        '  family: "Inter",',
    ]
    for _, label in WEIGHTS:
        body.append('  %s: "%s",' % (label, blobs[label]))
    body.append("  charset: %s," % json.dumps(charset))
    body.append("};")
    text = "\n".join(body) + "\n"

    if args.check:
        if not os.path.exists(OUT):
            sys.exit("fonts.js does not exist — run without --check")
        have = open(OUT).read()
        if have != text:
            sys.exit("FONT DRIFT. Rebuilding fonts.js from dev/inter.woff2 does not\n"
                     "reproduce the committed file. The embedded font is part of every exported\n"
                     "PDF, so this breaks reprint matching. Investigate before regenerating.")
        print("  fonts.js reproduces exactly from dev/inter.woff2")
        return

    with open(OUT, "w") as fh:
        fh.write(text)

    print("wrote " + OUT + "  (%d bytes)" % os.path.getsize(OUT))
    print("\n".join(report))


if __name__ == "__main__":
    main()
