#!/usr/bin/env python3
"""Vendor the puzzle engine out of the Zaney Sudoku site.

The books in this repo are reproducible only while the generator that dealt
them stays byte-identical. So the engine is not reimplemented here and not
edited here — it is copied verbatim out of zaneysudoku's index.html and
fingerprinted, and `--check` fails if the upstream copy has moved.

    python3 dev/sync-engine.py --from ../zaneysudoku/index.html
    python3 dev/sync-engine.py --check --from ../zaneysudoku/index.html

If the engine ever legitimately changes upstream, re-run without --check, then
regenerate and re-verify every book whose seeds you still intend to reprint.
"""
import argparse, hashlib, io, json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "engine.js")
LOCK = os.path.join(ROOT, "engine.lock.json")

# Content anchors, not markers: the upstream repo carries no edits of ours.
REGIONS = [
    ("engine",
     "/* =====================================================================\n   PUZZLE ENGINE",
     "function dailyHyperDiff(dayN){return dailyDiffFor(dayN);}"),
    # PAR lives in the UI half of index.html but the "About this difficulty"
    # front matter quotes it, so it comes along.
    ("par", "/* Par times are our own target benchmarks", "};"),
]


def carve(src, begin, end, label):
    i = src.find(begin)
    if i < 0:
        sys.exit("anchor for %r not found upstream — index.html has been restructured" % label)
    j = src.find(end, i)
    if j < 0:
        sys.exit("closing anchor for %r not found upstream" % label)
    return src[i:j + len(end)]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--from", dest="src", required=True, help="path to zaneysudoku/index.html")
    ap.add_argument("--check", action="store_true", help="verify only; do not write")
    a = ap.parse_args()

    src = io.open(a.src, encoding="utf-8").read()
    parts = [carve(src, b, e, name) for name, b, e in REGIONS]
    body = "\n\n".join(parts)
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()

    header = (
        "/* ==========================================================================\n"
        "   VENDORED FROM zaneysudoku/index.html — DO NOT EDIT THIS FILE.\n"
        "\n"
        "   The deterministic puzzle generator, copied verbatim so that a book dealt\n"
        "   today can be reprinted years from now byte for byte. Editing it here would\n"
        "   silently change every puzzle in every book in books.json.\n"
        "\n"
        "   Re-sync with:  python3 dev/sync-engine.py --from ../zaneysudoku/index.html\n"
        "   sha256: %s\n"
        "   ========================================================================== */\n\n"
    ) % digest

    if a.check:
        if not os.path.exists(LOCK):
            sys.exit("no engine.lock.json — run without --check first")
        lock = json.load(io.open(LOCK, encoding="utf-8"))
        if lock["sha256"] != digest:
            sys.exit(
                "ENGINE DRIFT.\n"
                "  vendored: %s\n"
                "  upstream: %s\n"
                "The site's generator has changed since this repo vendored it. Puzzles\n"
                "dealt from the same seeds may no longer match what you printed. Re-sync\n"
                "deliberately, then re-verify every book you still intend to reprint."
                % (lock["sha256"], digest))
        have = io.open(OUT, encoding="utf-8").read()
        if have != header + body:
            sys.exit("engine.js does not match its own lock file — it has been edited by hand")
        whole = hashlib.sha256(have.encode("utf-8")).hexdigest()
        if lock.get("sha256File") != whole:
            sys.exit("engine.js file hash does not match the lock file")
        print("engine matches upstream (sha256 %s…)" % digest[:16])
        return

    whole = header + body
    io.open(OUT, "w", encoding="utf-8").write(whole)
    io.open(LOCK, "w", encoding="utf-8").write(json.dumps({
        "sha256": digest,
        "sha256File": hashlib.sha256(whole.encode("utf-8")).hexdigest(),
        "source": "zaneysudoku/index.html",
        "regions": [r[0] for r in REGIONS],
        "bytes": len(body)
    }, indent=2) + "\n")
    print("wrote %s (%d bytes, sha256 %s…)" % (OUT, len(body), digest[:16]))


if __name__ == "__main__":
    main()
